version: '3.8'
services:
  api:
    container_name: api
    image: emp_api_img
    restart: always
    build: .
    networks:
      - employeeAPI
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    networks:
      - employeeAPI
    ports:
      - 5432:${DB_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres

volumes: 
 data: {}

networks:
  employeeAPI: {}